Added scheduled check for new Resonite versions

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -10,10 +10,42 @@ on:
         description: Version Override
         required: false
         type: string
+  schedule:
+  - cron: 37 1/3 * * *
 
 jobs:
+  check-for-resonite-update:
+    runs-on: ubuntu-slim
+    outputs:
+      UP_TO_DATE: ${{ steps.check-version.outputs.UP_TO_DATE }}
+    steps:
+    - name: Query Resonite version and check if matching tag exists
+      id: check-version
+      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
+      run: |
+        echo "Checking for current Resonite version..."
+        RESONITE_VERSION=$( curl -s https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/ResoniteAssemblies/refs/heads/main/Assemblies/RESONITE_VERSION | tr -d '\r\n ' ) || exit 1
+        if [ -z "$RESONITE_VERSION" ]
+        then
+          echo "Invalid Resonite version '$RESONITE_VERSION'!" >&2
+          exit 2
+        fi
+        echo "Searching for release tags built with Resonite $RESONITE_VERSION..."
+        MATCHING_RELEASES=$( git ls-remote --tags ${{github.repositoryUrl}} "*-$RESONITE_VERSION" ) || exit 3
+        if printf %s "$MATCHING_RELEASES" | grep -Fq "-$RESONITE_VERSION"
+        then
+          printf "Found:\n%s\n" "$MATCHING_RELEASES"
+          echo "Cancelling release workflow..."
+          echo "UP_TO_DATE=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "No matching releases found!"
+          echo "Continuing with release workflow..."
+        fi
   release:
     runs-on: ubuntu-latest
+    needs:
+      check-for-resonite-update
+    if: ${{ needs.check-for-resonite-update.UP_TO_DATE != 'true' }}
     permissions:
       contents: write
     steps:
