Added tags to mark failed builds and prevent repetition

diff --git a/.github/workflows/check-for-resonite-updates.yml b/.github/workflows/check-for-resonite-updates.yml
--- a/.github/workflows/check-for-resonite-updates.yml
+++ b/.github/workflows/check-for-resonite-updates.yml
@@ -2,6 +2,12 @@ name: Check for Resonite Updates
 
 on:
   workflow_dispatch:
+    inputs:
+      force-release:
+        description: Allows testing the workflow when a tag already exists (resulting in failure)
+        type: boolean
+        required: false
+        default: false
   schedule:
   - cron: 37 1/3 * * * #"/3" inicates one check every 3 hours.
 
@@ -11,6 +17,8 @@ jobs:
     outputs:
       UP_TO_DATE: ${{steps.check-version.outputs.UP_TO_DATE}}
       RESONITE_VERSION: ${{steps.check-version.outputs.RESONITE_VERSION}}
+    env:
+      FORCE_RELEASE: ${{ inputs.force-release }}
     steps:
     - name: Query Resonite version and check if matching tag exists
       id: check-version
@@ -31,22 +39,47 @@ jobs:
 
         echo "Searching for release tags built with Resonite $RESONITE_VERSION..."
         MATCHING_RELEASES="$( git ls-remote --tags 'https://github.com/${{github.repository}}' "*-$RESONITE_VERSION" )" || exit 3
-        if printf %s "$MATCHING_RELEASES" | grep -Fq -- "-$RESONITE_VERSION"
+        if printf %s "$MATCHING_RELEASES" | grep -Fq -- "-$RESONITE_VERSION" && [ -z "$FORCE_RELEASE" ]
         then
           printf "Found:\n%s\n" "$MATCHING_RELEASES"
-          echo "Cancelling release workflow..."
-          echo "UP_TO_DATE=true" >> "$GITHUB_OUTPUT"
+          if printf %s "$MATCHING_RELEASES" | grep -Fqv -- "failed-$RESONITE_VERSION"
+          then
+            echo "Cancelling release workflow..."
+            echo "UP_TO_DATE=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "No release found, only failures..."
+            exit 99 #fails the workflow so no build is attempted (new pushes with bug fixes trigger build-release directly)
+          fi
         else
           echo "No matching releases found!"
           echo "Continuing with release workflow..."
           echo "RESONITE_VERSION=$RESONITE_VERSION" >> "$GITHUB_OUTPUT"
         fi
   trigger-release:
-    needs:
-      check-for-resonite-update
+    needs: check-for-resonite-update
     if: needs.check-for-resonite-update.outputs.UP_TO_DATE != 'true'
     permissions:
       contents: write
     uses: $/.github/workflows/build-release.yml
     with:
       description: "Automatic rebuild with Resonite ${{needs.check-for-resonite-update.outputs.RESONITE_VERSION}}"
+  mark-failed-release:
+    runs-on: ubuntu-slim  
+    needs: trigger-release
+    if: needs.trigger-release.result == 'failure' #implies not skipped/not up to date
+    permissions:
+      contents: write
+    steps:
+    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
+    - name: Add tag and push
+      env:
+        FAILED_TAG: failed-${{needs.check-for-resonite-update.outputs.RESONITE_VERSION}}
+      run: |
+        echo "Marking the workflow run as failed so no further runs are attempted..."
+        git tag -f -- "$FAILED_TAG"
+        #:refs/tags/... would delete the tag if it already exists in remote.
+        git push origin ":refs/tags/$FAILED_TAG"
+        #refs/tags/... creates a new one.
+        git push origin "refs/tags/$FAILED_TAG"
+        exit 100 #fails the workflow
+
